name: flutter_project_template_riverpod
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  #* UI
  cached_network_image: ^3.3.0
  flash: ^3.1.0
  flutter_keyboard_visibility: ^5.4.1
  google_fonts: ^6.1.0
  gap:


  #* Icons
  flutter_vector_icons: ^2.0.0

  #* Firebase
  firebase_analytics: ^10.7.2
  firebase_core: ^2.24.0
  firebase_crashlytics: ^3.4.6
  firebase_messaging: ^14.7.6

  #* Local notification
  awesome_notifications: ^0.8.2

  #* Network
  dio: ^5.3.4
  pretty_dio_logger: ^1.3.1

  #* Dart data class
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  #* State management
  hooks_riverpod: ^2.4.9

  #* Functional programming
  fpdart: ^1.1.0

  #* Logging
  logging: ^1.2.0

  #* Routing
  go_router: ^12.1.3

  #* Persistent storage
  flutter_secure_storage: ^9.0.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  #* Localization
  intl: ^0.19.0

  #* Date Time util
  jiffy: ^6.2.1

    #* Utility
  flutter_svg: ^2.0.9
  path_drawing: ^1.0.1
  clipboard: ^0.1.3
  flutter_downloader: ^1.11.6
  video_thumbnail: ^0.5.3
  permission_handler: ^8.2.2
  html: ^0.15.4
  progressive_image: ^2.0.1
  http:



dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #* Code generators
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Medium.ttf
          style: normal
    - family: Acme
      fonts:
        - asset: assets/fonts/Acme-Regular.ttf
          style: normal
